import Sidebar from '../sidebar/Sidebar';
import Head from 'next/head';

export const Layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Logistics Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidebar />

      <main className="lg:ml-66 bg-gray-200 text-white p-8 h-screen">
        {children}
      </main>
    </div>
  );
};
