import Head from 'next/head';

import { useContext, useState, useEffect } from 'react';

import { DataContext } from '../Utils/DataContext';

import { useTheme } from 'next-themes';
//import components
import Theme from './Theme';
import Sidebar from '../components/Sidebar';
import TopNav from './TopNav';

import Modal from './Modal';

export const Layout = ({ children }) => {
  const { isOpen } = useContext(DataContext);

  const [isMounted, setIsMounted] = useState(false);

  const { setTheme } = useTheme();

  // useEffect(() => {
  //   setIsMounted(true);
  // }, [])

  return (
    <div className="layout__container relative">
      <Head>
        <title>Logistics Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidebar />

      <main className="bg-gray-50 dark:bg-black text-gray-500 dark:text-white pl-8 pr-14 md:pr-20 py-8 min-h-screen lg:ml-72 relative">
        <TopNav />
        {children}
      </main>
      <Theme setTheme={setTheme} />

      {isOpen ? <Modal /> : ''}
    </div>
  );
};
